server:
  port: 10011
spring:
  application:
    name: shortlink
  datasource:
    url: jdbc:mysql://47.120.60.61:3306/suts?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: suts
    password: 123456
  data:
    redis:
      host: 47.120.60.61
      port: 6379
      password: 123456
      timeout: 50000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
short-link:
  domain:
    default: 127.0.0.1:10011/restore


#http://localhost:10010/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
