server:
  port: 10012
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://47.120.60.61:3306/g-im-chat?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: gimchat
    password: LMLlml062424
  data:
    redis:
      host: 47.120.60.61
      port: 6379
      password: 123456
      timeout: 50000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



#http://localhost:10011/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
