system:
  port: 8080
  env: debug
  migrate: 1


# mysql:
#   host: 127.0.0.1
#   port: 3306
#   username: root
#   password: sjk12345
#   database: sfu
#   max_idle_conns: 100
#   max_open_conns: 1000

mysql:
  host: 47.120.60.61
  port: 3306
  username: gimchat
  password: LMLlml062424
  database: g-im-chat
  max_idle_conns: 100
  max_open_conns: 1000  

log:
  director: log
  retention_day: 7
  log_in_console: true
  levels: info
  format: json   # 输出格式:json,console
  level_encode: LowercaseColorLevelEncoder # 日志级别编码:LowercaseColorLevelEncoder,LowercaseLevelEncoder,UppercaseColorLevelEncoder,UppercaseLevelEncoder
  show_line: true
