system:
  port: 10014
  env: debug
  migrate: true


mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: sjk12345
  database: sfu
  max_idle_conns: 100
  max_open_conns: 1000

redis:
  addr: 127.0.0.1:6379
  password: sjk12345
  db: 0


jwt:
  expire: 604800 # 单位：秒
  secret: sfu
  issuer: sfu

log:
  director: log
  retention_day: 7
  log_in_console: true
  levels: info
  format: json   # 输出格式:json,console
  level_encode: LowercaseColorLevelEncoder # 日志级别编码:LowercaseColorLevelEncoder,LowercaseLevelEncoder,UppercaseColorLevelEncoder,UppercaseLevelEncoder
  show_line: true
